steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['pull', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']
    
    - name: 'gcr.io/cloud-builders/docker'
      args: ["buildx", "build", '--push',
                '--cache-to', 'type=inline,mode=max',
                '--cache-from', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
                "-t", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}",
                "-t", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest",
                "-f", "${_DOCKERFILE_DIR}/Dockerfile",
                "."]

    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest"]

    - name: "gcr.io/cloud-builders/gke-deploy"
      args:
      - run
      - --filename=./manifests/deployment.yaml
      - --image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${SHORT_SHA}
      - --location=us-central1-a
      - --cluster=gaw

substitutions:
    _IMAGE_NAME: "flightplanning"
    _DOCKERFILE_DIR: "."

timeout: 1200s