steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - -t
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'
      - -f
      - '${_DOCKERFILE_DIR}/Dockerfile'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_DEPLOY_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: "europe-west1-docker.pkg.dev"
  _AR_REPOSITORY: "cloud-run-source-deploy"
  _DEPLOY_REGION: "europe-west1"
  _SERVICE_NAME: "flightplanningtool"
  _DOCKERFILE_DIR: "."